/** Generated by [postcss-d-ts](https://github.com/YDFDarvin/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "__next": string|undefined
  "_hover": string|undefined
  "article": string|undefined
  "article__description": string|undefined
  "article__goals": string|undefined
  "article__stack": string|undefined
  "article__subjects": string|undefined
  "article__title": string|undefined
  "article__title--anchor": string|undefined
  "article__title--external": string|undefined
  "article__title--range": string|undefined
  "cv": string|undefined
  "cv__certifications": string|undefined
  "cv__chapter": string|undefined
  "cv__competences": string|undefined
  "cv__delimiter": string|undefined
  "cv__education": string|undefined
  "cv__experience": string|undefined
  "cv__languages": string|undefined
  "cv__links": string|undefined
  "cv__objectives": string|undefined
  "cv__projects": string|undefined
  "header": string|undefined
  "header__description": string|undefined
  "header__title": string|undefined
  "link": string|undefined
  "link--email": string|undefined
  "link--github": string|undefined
  "link--html": string|undefined
  "link--linkedin": string|undefined
  "link--location": string|undefined
  "link--npm": string|undefined
  "link--pdf": string|undefined
  "link--phone": string|undefined
  "link--skype": string|undefined
  "links_group": string|undefined
  "location": string|undefined
  "location__city": string|undefined
  "location__description": string|undefined
  "location__title": string|undefined
  "term": string|undefined
  "term--deprecated": string|undefined
}
